### ISSUE TITLE
Market API - Need an API to get the last traded price and volume for each token

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#102]
The market API needs the user to enter the market pair price and for that the user needs to know the last traded price and the volume for the tokens traded to perform an informed trade. Getting the price feed will also help developers automate the process of trading on their marketplaces to a great extent. Without the price feed it will severely impact the effectiveness of the marketplace for traders.

**Comment by VidereLicet** [comment]
You should be able to use the Query DSL for this:

market/list/executed/contract.amount/sum market=TKN/NXS where=results.timestamp>since(`24 hours`);
market/list/executed/order.amount/sum market=TKN/NXS where=results.timestamp>since(`24 hours`);

Above will give you trading volumes over last 24 hours for given token, use contract and order JSON values to access either the bid or the ask. You'll have to determine what token you want to measure volume in. The markeet=TKN/NXS are interchangable, if you do market=NXS/TKN it will reverse the contract and order calculations

Last traded price you do similar:

market/list/executed/price market=TKN/NXS limit=1

That should give you the last executed order's price using filter and limit to 1. You can get average price of last X orders too:

market/list/executed/price/mean markete=TKN/NXS limit=10

Above would give you average price of last 10 orders, so forth. Let me know if this doesn't work.
