### ISSUE TITLE
Checking total NXS on Tritium chain, the response is not accurate

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#123]
Was checking the total NXS on tritium and found that the response is not accurate. Its showing 12 million which is inaccurate, last month it was 50 million NXS on tritium.  This is using the latest merging branch

"version": "5.1.0-rc12 Tritium++ CLI [LLD][ARM aarch64]",
    "protocolversion": 3050000,

Tried -forcereindex and still the value is the same.

**API call and response:**
ubuntu@node2:~/LLL-TAO$ ./nexus register/list/finance:accounts,finance:trust/total/sum limit=none where='results.total>0 AND results.ticker=NXS'
{
    "total": 12766936.001
}
[Completed in 5615.745018 ms]

**Comment by VidereLicet** [comment]
You're probably not synced or not using the correct version, we are on rc18 and I did this on multiple nodes and get the exact same value, around 31MM.

**Comment by VidereLicet** [comment]
> 

Actually you were right, there was an issue with the sorting missing values that were equal, fixed with commit f633c7203ddd5dfb5c7acc9d8340cd4333708d84 keep in mind you will see some extra decimal places sometimes. Still don't have a good way to do this perfectly using our JSON library so will have to find a better way for future updates.

**Comment by VidereLicet** [comment]
> Was checking the total NXS on tritium and found that the response is not accurate. Its showing 12 million which is inaccurate, last month it was 50 million NXS on tritium. This is using the latest merging branch
> 
> "version": "5.1.0-rc12 Tritium++ CLI [LLD][ARM aarch64]", "protocolversion": 3050000,
> 
> Tried -forcereindex and still the value is the same.
> 
> **API call and response:** ubuntu@node2:~/LLL-TAO$ ./nexus register/list/finance:accounts,finance:trust/total/sum limit=none where='results.total>0 AND results.ticker=NXS' { "total": 12766936.001 } [Completed in 5615.745018 ms]

Actually you were right, there was an issue with the sorting missing values that were equal, fixed with commit https://github.com/Nexusoft/LLL-TAO/commit/f633c7203ddd5dfb5c7acc9d8340cd4333708d84 keep in mind you will see some extra decimal places sometimes. Still don't have a good way to do this perfectly using our JSON library so will have to find a better way for future updates.
