### ISSUE TITLE
Bootstrap No Longer Available to Download and Unable to Sync from Block 0

### ISSUE THREAD

**Issue by S4X1** [Nexusoft/LLL-TAO#170]
The bootstrap is no longer available to download and the protocol is unable to sync from Block 0 without getting stuck on the known block (known issue). @VidereLicet please fix this major issue. We no longer have a way to run a full node making the protocol extremely centralized.

**Comment by NamecoinGithub** [comment]
I started looking @ IP's @ the Break, and a Hong Kong Chi-Com IP pops out!

47.75.59.40

I blocked that IP and tried downloading the Blockchain again, and this time @ start of Sync it seemed to not throw type of Orphan before the other Hard Crash Block, but it usually always heals from restarting the Nexus Client!

I think Hard-code a Geo Block for Hong Kong!  Chi-Coms use it as a so called "Democratic" Digital Hub to spread as a Chi-Com Advance Guard!  But it's simple to Geo Block all HK as it has it's own Country Code HK, but otherwise I would recommending maybe blocking this Block of IP's!  Plus It would be a Revolutionary Act to proactively GEO Block the Chi-Coms who only spread Crime around the World and Drugs using Crypto, there has been nothing positive to ever come out of China in regards to Crypto development!  ASIC's will be history as they aren't QUANTUM SECURE~!  

Binance is owned by Canadian Born Chi-Com who mastered how the Kosher Bankers Manipulate the System and Setup his Persona as the Hallmark of A+ No Fraud Backup Fund Repair Asian Guy Perfectly!  

There is no real Scenario where Nexus Geo Blocking the Chi-Coms could be a bad thing as they provide nothing but wasteful destruction using their Now Privileged Position in the World brought about by Corrupt Elements within the Earth mainly the Kiken Mossad and Vatican once the Jewish Mafias worked out all the Rat Runs for the Chi-Coms to be their Slave labor Engine, to depose the West Morally and Financially dumping the Western Populations in horror of their Porn Capitals Hundred Billion a year Profit Industry @ same time propping up Chi-Com slave labor and Position in the World!  

Mostly without a proper Judge upon Earth with enough Power as even now Israel and Russia have both International Arrest Warrants from the UN War Crimes Tribunal but are readily ignored by all the main Actors within each Geo Blocked Sphere the Kosher Bankers have created of the Earth as Sanctions are the Kosher Bankers #1 Tool for Control!

47.75.59.40
47.75.0/255.0/255

**Comment by NamecoinGithub** [comment]
On a more Technical Note with Nexus Development

As far as I know Nexus Tritium can cut off the Blockchain from that fork in 2020!  So the Blockchain would be much smaller and start downloading from 2020 or something similar like that!  

The main Strategy I think Colin is trying to Solve is using the Old Nexus Bitcoin Code base to Soon have Nexus be able to Import Bitcoin Wallet.dat Files into their Sigchains ect...........and use it as Collateral for NXS/BTC Exchange within the Tritium Nexus GUI

But I think Monero is much better long term Strategy for many reasons, most of which I think it has a lot of Value Creation Compared to Bitcoin's 1.5 Trillion Market Cap Versus Monero 5 Billion Market Cap!  

As for this Blockchain Sync Business I am not too worried about it, I could setup my Computer to use Tor Firewall and get it to work, however I don't trust Tor, and Prefer Wireguard Firewall! 

I think it will get worked out anyway, the Next Release should be the Hard Fork Release, so it's just a matter of where to place the Hard Fork, but IDK in reality without a lot more discussion!  

Either way I think Nexus will as Colin said cut the Old Blockchain Bloat on the Old Code base!  That is where this Issue is stemming from on Bitcoin Code Nexus Blocks from 2015, Not the New Tritium Code base just to Clarify!  So it will get Resolved 1 way or another!

**Comment by NealHelman** [comment]
Bootstrap is now consistently available.
