### ISSUE TITLE
Mobile wallet, Changed password & PIN and after few weeks it reset automatically to the previous ones.

### ISSUE THREAD

**Issue by Aeonwise** [Nexusoft/LLL-TAO#51]
Mobile wallet user changed password and PIN, logged in with the new credentials and after few weeks, found the credentials were not working. Used the old credentials and found it working.

Looks like the credentials reset or are stored locally.

**Comment by VidereLicet** [comment]
Yeah, this is symptom of API not saving created transactions on disk, and not re-broadcasting them if still unconfirmed after a time. What most likely happened is they changed password, but had no connections to the network at the time they did, and once their wallet restarted, that tx was lost and so the blockchain only had record of their last confirmed transaction, that was still using their old credentials. This is being fixed with 5.1
