### ISSUE TITLE
From parameter missing in response of /ledger/get/transaction API

### ISSUE THREAD

**Issue by rayanfer32** [Nexusoft/LLL-TAO#81]
`v5.1.0`

http://api.nexus-interactions.io:8080/ledger/get/transaction?hash=01c763c0fead2ebcc8451709f3a3465e3fc4b8af11125b6dbf428ba1ef6d40018726cf73930bae64e558f6882c209ffd7e4aebfc5ed3b66a8bac9329313350d8&verbose=detail

from parameter is missing but it was available in the `v.5.0`

**Comment by VidereLicet** [comment]
from parameter was incorrectly included in the list of transactions pre 5.1, as this is not a piece of data on a given transaction, it is from another transaction that happened on another's sigchain.

**Comment by VidereLicet** [comment]
@rayanfer32 after contemplating your request a bit, I found a nice way to add from field in CREDITS without needing to decode and lookup previous transaction. I also included some extra logic for proof key, which will show data related to a proof for split dividend payments, otherwise proof key is not included and replaced with from key. You can test with latest build https://github.com/Nexusoft/LLL-TAO/commit/200e4fc3670e9a7b9b763e1a485e2e63f87e898e
