### ISSUE TITLE
Add 'recovery' flag back into `sessions/status/local` result

### ISSUE THREAD

**Issue by Qrysto** [Nexusoft/LLL-TAO#92]
Please put the `recovery` flag (whether sigchain has already set a recovery phrase) back into `sessions/status/local`. The wallet UI needs it to decide how to show menu items to user. If it's not included in `sessions/status/local` result, the UI will have to do extra calls every few seconds to get the info it needs.

**Comment by VidereLicet** [comment]
Session is for session level data, such as things related to active login. Profiles/status/master shows the ledger and sigchain level data like recovery, so use profiles/status/master to see this data. The same for the username since this is a profile related data, not session related data that is temporary.
